server:
  port: 8080
  servlet:
    session:
      timeout: 2d
      cookie:
        max-age: 2d
spring:
  data:
    redis:
      host: 82.156.19.215
      port: 6379
      password: 2003711m
      lettuce:
        pool:
          max-active: -1
          max-idle: 10

swust:
  close-time: 1
  start-time: 6
  api:
    breaker:
      threshold: 3
      break-millisecond: 120000
      circle: 60000

cache:
  default:
    expire-time: 46800

logging:
  file:
    path: ./swust-log
